<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>AxialCompressorDesigner</RootNamespace>
    <AssemblyName>AxialCompressorDesigner</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>CS1591</NoWarn>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Authors>Quasar Solutions Lab</Authors>
    <Product>QUASAR Phy-AC</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PicoGK" Version="2.2.0" />
  </ItemGroup>
</Project>
